const UserActionTypes = {
    SIGN_IN_START: "SIGN_IN_START",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS,",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
    SIGN_OUT_START: "SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
    SET_POP_UP: "SET_POP_UP",
    VERIFY_EMAIL_START: "VERIFY_EMAIL_START",
    VERIFY_EMAIL_SUCCESS: "VERIFY_EMAIL_SUCCESS",
    VERIFY_EMAIL_FAILURE: "VERIFY_EMAIL_FAILURE",
  };
  export default UserActionTypes;